services:
  frontend:
    container_name: frontend
    build: ./front-end
    ports:
      - "443:443"
    depends_on:
      - backend
    environment:
      - PORT=443
      - HTTPS=true 
      - SSL_CRT_FILE=ca/cert.crt 
      - SSL_KEY_FILE=ca/cert.key

  backend:
    container_name: backend
    build: ./back-end
    ports:
      - "3001:3001"